# Generated by Django 4.1.2 on 2022-10-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperItems',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('item_type', models.CharField(max_length=255)),
                ('item_medium', models.CharField(max_length=255)),
                ('item_image_url', models.CharField(max_length=255)),
                ('item_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VAItems',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('item_type', models.CharField(max_length=255)),
                ('item_medium', models.CharField(max_length=255)),
                ('item_image_url', models.CharField(max_length=255)),
                ('item_location', models.CharField(max_length=255)),
            ],
        ),
    ]
