# Generated by Django 4.1.2 on 2022-10-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CooperItems',
            new_name='CooperItem',
        ),
        migrations.RenameModel(
            old_name='VAItems',
            new_name='VAItem',
        ),
    ]
